apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ppkwlb8yk-python
  janus-idp.io/tekton: ppkwlb8yk-python
  backstage.io/kubernetes-id: ppkwlb8yk-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ppkwlb8yk-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
