apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ppkwlb8yk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ppkwlb8yk-python 
  name: ppkwlb8yk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ppkwlb8yk-python 
